spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.146.140/mydb?useSSL=false&serverTimeZone=GMT%2B8&characterEncoding=UTF-8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver                                                     #allowMultiQueries允许批量操作
    url: jdbc:p6spy:mysql://192.168.146.140/mydb?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  profiles:
    active: dev
logging:
  level:
    root: warn
    com.lvym.mybatisplus.dao: trace
  pattern:
    console: '%p%m%n'
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
#    sql-parser-cache: true #3.1.1之前版本需要配置
